# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create --name testenv --file requirements.txt

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda activate testenv
            flake8 --exclude=venv* --statistics
            pytest -v --cov=conversion
      # Step 4: save result
      # - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test-results
